// src/shared/permissions/ability.ts
import { AppRole, ROLES } from './roles';
import { Permission, PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.COMPANY_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.RESPONSABLE]: [
    // Equivalents for Responsable
    PERMISSIONS.DASHBOARD_VIEW,
    
    PERMISSIONS.WORKORDER_VIEW,
    PERMISSIONS.WORKORDER_CREATE,
    PERMISSIONS.WORKORDER_UPDATE,
    PERMISSIONS.WORKORDER_ASSIGN,
    PERMISSIONS.WORKORDER_START,
    PERMISSIONS.WORKORDER_SUSPEND,
    PERMISSIONS.WORKORDER_FINISH,
    PERMISSIONS.WORKORDER_CLOSE,
    PERMISSIONS.WORKORDER_EXPORT,

    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_CREATE,
    PERMISSIONS.EQUIPMENT_UPDATE,
    PERMISSIONS.EQUIPMENT_IMPORT,
    PERMISSIONS.EQUIPMENT_EXPORT,

    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.INCIDENT_UPDATE,
    PERMISSIONS.INCIDENT_VALIDATE,

    PERMISSIONS.PREVENTIVE_VIEW,
    PERMISSIONS.PREVENTIVE_CREATE,
    PERMISSIONS.PREVENTIVE_UPDATE,
    PERMISSIONS.PREVENTIVE_EXECUTE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_MOVE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_CREATE,
    PERMISSIONS.REPORT_EXPORT,
  ],
  [ROLES.CHEF_EQUIPE]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.WORKORDER_VIEW,
    PERMISSIONS.WORKORDER_CREATE,
    PERMISSIONS.WORKORDER_UPDATE,
    PERMISSIONS.WORKORDER_ASSIGN,
    PERMISSIONS.WORKORDER_CLOSE,

    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_UPDATE,

    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.INCIDENT_VALIDATE,

    PERMISSIONS.PREVENTIVE_VIEW,
    PERMISSIONS.PREVENTIVE_CREATE,
    PERMISSIONS.PREVENTIVE_UPDATE,
    PERMISSIONS.PREVENTIVE_EXECUTE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MOVE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  [ROLES.TECHNICIEN]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.WORKORDER_VIEW,
    PERMISSIONS.WORKORDER_START,
    PERMISSIONS.WORKORDER_SUSPEND,
    PERMISSIONS.WORKORDER_FINISH,

    PERMISSIONS.EQUIPMENT_VIEW,

    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_CREATE,

    PERMISSIONS.PREVENTIVE_VIEW,
    PERMISSIONS.PREVENTIVE_EXECUTE,

    PERMISSIONS.INVENTORY_VIEW,
  ],
  [ROLES.PRODUCTION]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.INCIDENT_CREATE,
  ],
  [ROLES.MAGASINIER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_MOVE,
  ]
};
